# Generated by Django 2.1.1 on 2018-10-04 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('titulo', models.CharField(max_length=150, verbose_name='Titulo')),
                ('autorizado', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não'), ('Em Análise', 'Em Análise')], default='Em Análise', max_length=12, verbose_name='autorizadoo')),
                ('feedback', models.TextField(verbose_name='Feedback')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_turma', models.CharField(max_length=250, verbose_name='turma')),
                ('turno', models.CharField(choices=[('s/t', 'Sem turno'), ('manhã', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite')], max_length=10, verbose_name='turno')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_nascimento', models.DateField(verbose_name='data de nascimento')),
                ('imei_celular', models.CharField(max_length=250, unique=True, verbose_name='IMEI')),
                ('ip_celular', models.CharField(max_length=250, verbose_name='IP')),
                ('mac_celular', models.CharField(max_length=250, unique=True, verbose_name='MAC')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Turma')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mensagens',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensagens_usuario', to='app.Usuario'),
        ),
    ]
