# Generated by Django 2.1.1 on 2018-10-06 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='imei_celular',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='mac_celular',
        ),
    ]
